version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todolist_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todolist_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: ./app
    container_name: todolist_app
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todolist_network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx:alpine
    container_name: todolist_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - todolist_network

networks:
  todolist_network:
    driver: bridge
    name : net_tekser_${GROUP_NAME:-E1}

volumes:
  db_data: 
    name: mysql_data_${GROUP_NAME:-E1}
    driver: local
